version: '3'
services:
  blog-app:
    image: blog-website
    container_name: blog-website-container
    environment:
      NODE_OPTIONS: --max_old_space_size=4096
    build: .
    restart: unless-stopped
    volumes:
      - ./:/usr/local/nonroot/app/:cached
      - ./logs:/var/log/app/:cached
      - /usr/local/nonroot/app/node_modules
    command: yarn run serve
    env_file:
      - .env
    ports:
      - "9700:9700"
